# Generated by Django 3.2.5 on 2021-07-13 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'permissions': (('can_add_row', 'Can add new rows'), ('can_update_row', 'Can update rows'), ('can_delete_rows', 'Can delete rows'))},
        ),
        migrations.AlterModelOptions(
            name='menu_item',
            options={'permissions': (('can_add_row', 'Can add new rows'), ('can_update_row', 'Can update rows'), ('can_delete_rows', 'Can delete rows'))},
        ),
    ]
