# Generated by Django 3.2.5 on 2021-07-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210713_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='meal_category',
            field=models.CharField(blank=True, choices=[('main_course', 'Main Course'), ('drinks', 'Drinks')], max_length=50, null=True),
        ),
    ]
