# Generated by Django 3.2.5 on 2021-08-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_item_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
