# Generated by Django 3.2.5 on 2021-07-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210713_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False),
        ),
    ]
