# Generated by Django 3.2.5 on 2021-07-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
