# Generated by Django 3.2.5 on 2021-07-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_item_meal_category'),
        ('orders', '0007_alter_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meal',
        ),
        migrations.AddField(
            model_name='order',
            name='meal',
            field=models.ManyToManyField(null=True, to='menu.Menu_Item'),
        ),
    ]
