# Generated by Django 3.2.5 on 2021-08-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_item_meal_category'),
        ('orders', '0008_auto_20210718_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meal',
            field=models.ManyToManyField(to='menu.Menu_Item'),
        ),
    ]
