# Generated by Django 3.2.5 on 2021-08-12 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_item_meal_category'),
        ('orders', '0009_alter_order_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meal',
        ),
        migrations.AddField(
            model_name='order',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu_item'),
        ),
    ]
