# Generated by Django 3.2.5 on 2021-08-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210813_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
