# Generated by Django 3.2.5 on 2021-08-22 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderimage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 22, 19, 29, 35, 361088), null=True),
        ),
    ]
