# Generated by Django 3.2.5 on 2021-08-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orderimage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
