# Generated by Django 3.2.5 on 2021-08-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_databaseinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('current_total_size', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='database_info',
            field=models.BooleanField(null=True),
        ),
    ]
